### ISSUE TITLE
When a pooled connection is closed, the actual connection should not be made available after it has been closed internally

### ISSUE THREAD

**Issue by mkulak** [reactiverse/reactive-pg-client#131] opened 2018-07-18 17:26 UTC
After scheduled upgrade of running postgres our application came to a strange state:
every request to db throw `io.vertx.core.VertxException: Connection not open CLOSED`. After manually restarting every pod of our app it healed (during startup each instance was able to connect to db as usual). 
We use connection pool like that: 
```kotlin
    PgClient.pool(vertx, PgPoolOptions().apply {
        database = config.database
        host = config.host
        port = config.port
        user = config.user
        password = config.password
        isSsl = true
        isTrustAll = true
        maxSize = 10
        cachePreparedStatements = true
    })
```
Unfortunately I don't have reproducer for this situation. Maybe you will be able to figure out the cause by stacktrace.

Pg-client version: 0.8.0
Postgres version: PostgreSQL 10.4 (Ubuntu 10.4-2.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit

Full stacktrace:
```
io.vertx.core.VertxException: Connection not open CLOSED
at io.reactiverse.pgclient.impl.SocketConnection.bilto(SocketConnection.java:193)
at io.reactiverse.pgclient.impl.CommandBase.foo(CommandBase.java:54)
at io.reactiverse.pgclient.impl.SocketConnection.schedule(SocketConnection.java:181)
at io.reactiverse.pgclient.impl.ConnectionPool$PooledConnection.schedule(ConnectionPool.java:81)
at io.reactiverse.pgclient.impl.PgConnectionImpl.schedule(PgConnectionImpl.java:60)
at io.reactiverse.pgclient.impl.PgClientBase.lambda$preparedQuery$0(PgClientBase.java:41)
at io.reactiverse.pgclient.impl.SocketConnection$CachedPreparedStatement.get(SocketConnection.java:112)
at io.reactiverse.pgclient.impl.PrepareStatementCommand.foo(PrepareStatementCommand.java:60)
at io.reactiverse.pgclient.impl.SocketConnection.schedule(SocketConnection.java:181)
at io.reactiverse.pgclient.impl.ConnectionPool$PooledConnection.schedule(ConnectionPool.java:81)
at io.reactiverse.pgclient.impl.PgConnectionImpl.schedule(PgConnectionImpl.java:60)
at io.reactiverse.pgclient.impl.PgConnectionImpl.lambda$schedule$0(PgConnectionImpl.java:64)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment] 2018-07-20 07:18
thanks for reporting I will have a look

**Comment by EmadAlblueshi** [comment] 2018-07-21 21:49
@vietj I think this happened because we are [handling cache](https://github.com/reactiverse/reactive-pg-client/blob/176a42e6cbb705c4db3ed56933bd5e3715cdbd0e/src/main/java/io/reactiverse/pgclient/impl/SocketConnection.java#L171) before [checking the status](https://github.com/reactiverse/reactive-pg-client/blob/176a42e6cbb705c4db3ed56933bd5e3715cdbd0e/src/main/java/io/reactiverse/pgclient/impl/SocketConnection.java#L193) of connection WDYT ?

**Comment by mkulak** [comment] 2018-07-30 12:12
This situation happened again. It's a blocker for us

**Comment by vietj** [comment] 2018-07-30 12:34
sorry to hear that @mkulak I will have a look today

**Comment by vietj** [comment] 2018-07-30 12:34
do you have more details ?

**Comment by vietj** [comment] 2018-07-30 21:32
@mkulak can you set an exception handler to know what is happening to the connection ?

```
conn.exceptionHandler(err -> {
  // Log the error
});
```

so we know the reason that force all connection to be closed.

can you also upgrade the client version to 0.9.0 ?

**Comment by mkulak** [comment] 2018-07-30 21:41
Will try to gather more details and also install exception handler.

**Comment by mkulak** [comment] 2018-08-10 09:46
UPD:
We have 2 different services running reactive-pg-client (each talks to it's own postgres). 
Initially both of them were running version 0.8.0. We ran into this bug 2 times. Both times it hit both services simultaneously. 

After that in one service we bumped version to 0.9.0, installed exception handler with logging and added try-catch for this specific exception. In catch block we simply recreate pool. Other service left untouched. 

Today bug reproduced (with usual symptoms) in second service (unmodified one). First service didn't encounter any problem (no exceptions in logs at all). So either we were unlucky and situation leading to a bug didn't appear for first service OR this bug was fixed in 0.9.0

Now I'm going to bump library version on second service (without adding custom pool recreation logic) and see what will happen next.

**Comment by vietj** [comment] 2018-08-11 18:07
@mkulak let us know about how it goes

**Comment by AlxGDev** [comment] 2018-08-27 01:55
I've run into the same issue today on 0.10.1
From what I can tell the following caused it:
`getConnection().compose(connection -> {
			LOGGER.info("Got Connection");
			connection.closeHandler(c->{
				LOGGER.info("closing");
			});
			connection.exceptionHandler(h->{
		    	  LOGGER.error("Connection Exception: "+h);
		        });
			connection.preparedQuery(sql, tuple, r -> {
					if (r.succeeded()) {
						future.complete(convertRowSet(r.result()));
						
					} else {
						future.fail(r.cause());
					}
					connection.close();
				});
		}, future);`
When there is a class cast exception in connection.preparedQuery (due to wrong type for the db field), the output will be something like:
Got Connection
Connection Exception: ClassCastException
Output of future handler: ClassCastException
closing

Then, when the same query is tried again the exceptionHandler won't get called, instead the ouput will be something like:
Got Connection
Output of future handler: Connection not open CLOSED

And this continues for subsequent retries of the same query. If I remove connection.close() then the first error log repeats with each retry, no "Connection not open CLOSED", but according to the docs the connection should be closed after handling the query. I am also unsure why the closeHandler is called when I don't call connection.close()

**Comment by vietj** [comment] 2018-08-28 16:08
@AlxGDev can you provide a reproducer project ?

**Comment by AlxGDev** [comment] 2018-08-29 22:37
@vietj I created a reproducer project here: https://github.com/AlxGDev/PgClientIssue131Reproducer 
Please me know if you need anything changed or detect an obvious error on my part, thank you.

**Comment by AlxGDev** [comment] 2018-08-30 08:10
@vietj Thank you, I added some additional info to show that even correct queries fail once the "Connection not open CLOSED" Exception occurs.

**Comment by vietj** [comment] 2018-08-30 10:01
@AlxGDev can you elaborate on how  to use this ?

**Comment by vietj** [comment] 2018-08-30 12:33
@AlxGDev thanks I've been able to reproduce and fix multiple bugs

**Comment by AlxGDev** [comment] 2018-08-30 12:34
@vietj Awesome, glad to hear it

**Closed** 2018-08-30 12:36 UTC
Labels: bug

**Comment by vietj** [comment] 2018-08-30 12:44
@AlxGDev a jar should be available in Sonatype OSS snapshot repository, can you have a check ?

**Comment by AlxGDev** [comment] 2018-08-31 09:36
@vietj Yes, it works now as expected with version 0.10.2, thanks a lot!

**Comment by vietj** [comment] 2018-08-31 09:44
@AlxGDev your reproducer helped a lot resolving issues for 0.10.2
